packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

onlyBuiltDependencies:
  - '@prisma/engines'
  - argon2
  - less
  - prisma
  - sharp
  - simple-git-hooks
