#!/bin/bash

# Настройки
OUTPUT_FILE="full_system_context.md"
TEMP_TOC=".temp_toc.md"
PROJECT_NAME=$(basename "$PWD")
BUILD_DATE=$(date "+%Y-%m-%d %H:%M:%S")

# Очистка старых файлов
rm -f "$OUTPUT_FILE" "$TEMP_TOC"

echo "--- Запуск сборки контекста для проекта: $PROJECT_NAME ---"

# 1. Заголовок и метаданные
{
  echo "# System Context: $PROJECT_NAME"
  echo "Generated by Eva-Assembler on: $BUILD_DATE"
  echo "---"
  echo "## Table of Contents"
} >>"$OUTPUT_FILE"

# 2. Сбор списка всех подходящих файлов (Markdown)
# Исключаем сам выходной файл и скрытые папки
mapfile -t ALL_FILES < <(find . -type f -name "*.md" ! -name "$OUTPUT_FILE" ! -path "*/.*" | sort -V)

if [ ${#ALL_FILES[@]} -eq 0 ]; then
  echo "Ошибка: Markdown файлы не найдены."
  exit 1
fi

# 3. Генерация Оглавления (TOC)
echo "Генерация оглавления для ${#ALL_FILES[@]} файлов..."
for file in "${ALL_FILES[@]}"; do
  # Убираем ./ в начале пути
  clean_path="${file#./}"
  # Создаем якорь (нижний регистр, замена пробелов и спецсимволов на дефисы)
  anchor=$(echo "$clean_path" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g')
  echo "- [$clean_path](#$anchor)" >>"$TEMP_TOC"
done

cat "$TEMP_TOC" >>"$OUTPUT_FILE"
rm "$TEMP_TOC"

echo -e "\n---\n" >>"$OUTPUT_FILE"

# 4. Основной цикл сборки
count=0
for file in "${ALL_FILES[@]}"; do
  clean_path="${file#./}"
  anchor=$(echo "$clean_path" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g')

  echo "Обработка [$((++count))/${#ALL_FILES[@]}]: $clean_path"

  {
    echo -e "\n<a name=\"$anchor\"></a>"
    echo ""
    echo "# FILE: $clean_path"
    echo -e "---"
    # Читаем контент файла
    cat "$file"
    echo -e "\n"
    echo ""
    echo -e "---"
  } >>"$OUTPUT_FILE"
done

# 5. Статистика
TOTAL_LINES=$(wc -l <"$OUTPUT_FILE")
{
  echo -e "\n# Build Summary"
  echo "- Total files merged: ${#ALL_FILES[@]}"
  echo "- Total lines generated: $TOTAL_LINES"
  echo "- Build status: Success"
} >>"$OUTPUT_FILE"

echo "---"
echo "Сборка завершена успешно!"
echo "Файл: $OUTPUT_FILE"
echo "Всего файлов: ${#ALL_FILES[@]}"
echo "Всего строк: $TOTAL_LINES"
